### ISSUE TITLE
Add the "Create Issue Branch" bot

### ISSUE THREAD

**Issue by deepakDOTexe** [Elevate-Lab/Import-Template#10]
https://probot.github.io/apps/create-issue-branch/

Create Issue Branch is a GitHub app that creates a new branch after assigning an issue.

**Comment by Cybertron-Avneesh** [comment]
@deepakDOTexe sir,
**A request to install Create Issue Branch has been submitted on the @Elevate-Lab account.**
Allow **Create Issue Branch** bot to access repositories.

**Comment by Tlazypanda** [comment]
@Cybertron-Avneesh access granted

**Comment by Tlazypanda** [comment]
@all-contributors add @deepakDOTexe for maintenance
