### ISSUE TITLE
Add the "Delete merged branch" bot

### ISSUE THREAD

**Issue by deepakDOTexe** [Elevate-Lab/Import-Template#11]
https://probot.github.io/apps/delete-merged-branch/

Delete merged branch is a GitHub app that automatically deletes a branch after it's merged.

**Comment by Cybertron-Avneesh** [comment]
@deepakDOTexe sir
A request to install Delete merged branch has been submitted on the @Elevate-Lab account.
Please allow the bot to access repositories.

**Comment by Tlazypanda** [comment]
@Cybertron-Avneesh access granted
