### ISSUE TITLE
Add the "welcome" bot

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/Import-Template#4]
Welcome is a simple way to welcome new users based off maintainer defined comments.

The 3 plugins it combines with are new-issue-welcome(Comment to be posted to on first time issues) , new-pr-welcome(Comment to be posted to on PRs from first time contributors in your repository) and first-pr-merge(Comment to be posted to on pull requests merged by a first time user).

We can setup Welcome bot by adding the GitHub App to our organization repositories and configuring .github/config.yml according to the content of the messages we want.

This will make the new contributors feel welcomed and at ease in interacting with the community.

Adding this to the import-me repository will ensure that this config is added to all new repositories.

https://github.com/apps/welcome

**Comment by siddhantdrk** [comment]
@Tlazypanda  Mam I would like to work on this issue.

**Comment by Tlazypanda** [comment]
Hey @siddhantdrk sure go ahead 🎉

**Comment by Tlazypanda** [comment]
Closed via #12
